apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-rest-api-jwt-docker-deployment
  labels:
    app: go-rest-api-jwt-docker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-rest-api-jwt-docker
  template:
    metadata:
      labels:
        app: go-rest-api-jwt-docker
    spec:
      containers:
      - name: go-rest-api-jwt-docker
        image: go-rest-api-jwt-docker:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: go-rest-api-jwt-docker-service
  labels:
    service: go-rest-api-jwt-docker
spec:
  type: NodePort
  selector:
    app: go-rest-api-jwt-docker
  ports:
  - port: 8000
    targetPort: 8000